### ISSUE TITLE
Duke Fails On Large Dataset

### ISSUE THREAD

**Issue by phorne-uncharted** [NewKnowledge/duke-d3m-wrapper#2]
Trying to run the LL1_336_MS_Geolife_transport_mode_prediction dataset through Duke causes a crash.

Pipeline submitted:
Executing pipeline pipelineDescription {
  name: "wellington"
  outputs {
    data: "steps.1.produce"
  }
  steps {
    primitive {
      primitive {
        id: "4b42ce1e-9b98-4a25-b68e-fad13311eb65"
        version: "0.3.0"
        python_path: "d3m.primitives.datasets.DatasetToDataFrame"
        name: "Dataset to DataFrame converter"
        digest: "85b946aa6123354fe51a288c3be56aaca82e76d4071c1edc13be6f9e0e100144"
      }
      arguments {
        key: "inputs"
        value {
          container {
            data: "inputs.0"
          }
        }
      }
      outputs {
        id: "produce"
      }
    }
  }
  steps {
    primitive {
      primitive {
        id: "46612a42-6120-3559-9db9-3aa9a76eb94f"
        version: "1.1.1"
        python_path: "d3m.primitives.distil.duke"
        name: "duke"
        digest: "ea522d2adc756c3ad76f5848d28cd396304d4dfdc0cc55aa8b90fbaf04e8fc30"
      }
      arguments {
        key: "inputs"
        value {
          container {
            data: "steps.0.produce"
          }
        }
      }
      outputs {
        id: "produce"
      }
    }
  }
}
inputs {
  dataset_uri: "file:///output/d3m/LL1_336_MS_Geolife_transport_mode_prediction/TRAIN/dataset_TRAIN/merged/datasetDoc.json"
}

Executing primitive: duke
Hyperparams:
{}

Logging Output:
loading word2vec embedding model
loading dataset from pandas DataFrame

**Comment by phorne-uncharted** [comment]
The dataset has 3768251 rows.

Sample data:
d3mIndex,date_time,user_id,track_id,lat_lon,altitude,num_days,Transportation
180198,2008-03-28 14:54:40,10,20080328144824,"39.894178000000004,116.3182",-777.0,39535.621296296296,train
180199,2008-03-28 14:55:14,10,20080328144824,"39.894505,116.321132",-777.0,39535.6216898148,train
180200,2008-03-28 14:56:13,10,20080328144824,"39.894953,116.326452",-777.0,39535.6223726852,train
180201,2008-03-28 14:57:12,10,20080328144824,"39.8946,116.33254199999999",-777.0,39535.6230555556,train
180202,2008-03-28 14:58:11,10,20080328144824,"39.889621999999996,116.33703999999999",-777.0,39535.6237384259,train
180203,2008-03-28 14:59:10,10,20080328144824,"39.88209000000001,116.338353",-777.0,39535.6244212963,train
180204,2008-03-28 15:00:10,10,20080328144824,"39.873872999999996,116.33845500000001",-777.0,39535.625115740695,train
180205,2008-03-28 15:01:09,10,20080328144824,"39.865182,116.338058",-777.0,39535.6257986111,train
180206,2008-03-28 15:02:08,10,20080328144824,"39.855403,116.33771000000002",-777.0,39535.6264814815,train
180207,2008-03-28 15:03:07,10,20080328144824,"39.844532,116.33436200000001",-777.0,39535.627164351805,train
180208,2008-03-28 15:04:06,10,20080328144824,"39.831557000000004,116.32811000000001",-777.0,39535.627847222204,train
180209,2008-03-28 15:05:06,10,20080328144824,"39.816621999999995,116.322978",-777.0,39535.6285416667,train
180210,2008-03-28 15:06:05,10,20080328144824,"39.801413000000004,116.317968",-777.0,39535.629224537,train
180211,2008-03-28 15:07:04,10,20080328144824,"39.7854,116.311732",-777.0,39535.629907407405,train
180212,2008-03-28 15:08:03,10,20080328144824,"39.76939,116.305378",-777.0,39535.6305902778,train
180213,2008-03-28 15:09:02,10,20080328144824,"39.754487,116.299953",-777.0,39535.6312731481,train
180214,2008-03-28 15:10:02,10,20080328144824,"39.744377,116.30384",-777.0,39535.6319675926,train
180215,2008-03-28 15:11:01,10,20080328144824,"39.737025,116.30875800000001",-777.0,39535.632650463,train
180216,2008-03-28 15:12:37,10,20080328144824,"39.728613,116.314788",-777.0,39535.6337615741,train

**Comment by azunre** [comment]
I took a look at the data. Yes, it is likely a memory issue. Duke should be able to use only a subsample of the rows to summarize. I am working out how best to add subsampling to the primitive..

**Comment by azunre** [comment]
@jlgleason see above ^^
